# Generated by Django 6.1 on 2026-08-25 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the quiz (e.g. Python Basics, Django Fundamentals)', max_length=200)),
                ('description', models.TextField(help_text='Brief description explaining what this quiz covers')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the quiz was created')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this quiz is published and accessible to students')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question prompt or problem statement')),
                ('option1', models.CharField(help_text='First multiple choice option', max_length=255)),
                ('option2', models.CharField(help_text='Second multiple choice option', max_length=255)),
                ('option3', models.CharField(help_text='Third multiple choice option', max_length=255)),
                ('option4', models.CharField(help_text='Fourth multiple choice option', max_length=255)),
                ('correct_answer', models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], help_text='Select which option is the correct answer', max_length=10)),
                ('quiz', models.ForeignKey(help_text='The quiz this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
